---

- name: Remove bad users
  community.routeros.command:
    commands: >-
      /user disable {{ item.name }}
  loop: "{{ administrator_accounts }}"
  when: not item.account_enabled
  tags: configure_user

- name: Create good users
  community.routeros.command:
    commands: >-
      /user add name={{ item.name }} password={{ item.password | default(default_user_password) }}
      group={{ item.mikrotik.group | default('read') }} comment="Ansible managed"
  no_log: true
  register: result_create_user
  changed_when: result_create_user.stdout | regex_search('user with the same name already exists') is none
  failed_when: ( result_create_user.stdout | regex_search('expected end of command') is not none ) or
      ( result_create_user.stdout | regex_search('syntax error') is not none )
  loop: "{{ administrator_accounts }}"
  when: item.account_enabled
  tags: configure_user
