---

- name: Lookup ssh key for "{{ item.name }}"
  ansible.builtin.set_fact:
    ssh_details:
      username: "{{ item.name }}"
      pub_ssh_keys: "{{ lookup('url', 'https://github.com/{}.keys'.format(item.name)).split(',') }}"
  delegate_to: localhost
  run_once: true
  tags: add_ssh_key

- name: Add ssh key for "{{ item.name }}"
  community.routeros.command:
    commands: >-
      /user ssh-keys add key="{{ outer_item }}" user="{{ item.name }}"
  when: outer_item | regex_search('ssh-rsa')
  loop: "{{ ssh_details.pub_ssh_keys }}"
  loop_control:
    loop_var: outer_item
  tags: add_ssh_key
