---

- name: Ansible managed chr
  hosts: private-chr-vds
  strategy: linear
  gather_facts: false
#  ignore_unreachable: false

  tasks:

    - name: Ensure that sshpass is installed
      ansible.builtin.command: which sshpass
      run_once: true
      ignore_errors: true
      changed_when: false
      register: local_sshpass
      delegate_to: localhost

    - name: Debug local_sshpass
      ansible.builtin.debug:
        var: local_sshpass

    - name: Fail if sshpass is not installed
      ansible.builtin.fail:
        msg: >-
          Playbook requrie sshpass to use password authenication, please install
          sshpass and re-run same playbook again.
          You can found details in https://www.redhat.com/sysadmin/ssh-automation-sshpass
      when: local_sshpass.stdout | length == 0

    - name: Gather export (with password authentication)
      ansible.builtin.command: >-
        {{ local_sshpass.stdout }} -p '{{ ansible_ssh_pass }}' ssh -o StrictHostKeyChecking=no {{ ansible_user }}@{{ ansible_ssh_host }} '/export terse'
      register: mikrotik_pass_export
      changed_when: mikrotik_export.stdout | length != 0
      failed_when: mikrotik_export.stdout | length == 0
      when: ansible_ssh_pass is defined
      delegate_to: localhost

    - name: Debug mikrotik_export1
      ansible.builtin.debug:
        var: mikrotik_pass_export

    - name: Gather export (with key authentication)
      ansible.builtin.command: >-
        ssh -o StrictHostKeyChecking=no {{ ansible_user }}@{{ ansible_ssh_host }} '/export terse'
      changed_when: mikrotik_export.stdout | length != 0
      failed_when: mikrotik_export.stdout | length == 0
      when: ansible_ssh_pass is not defined
      register: mikrotik_export
      delegate_to: localhost

    - name: Debug mikrotik_export2
      ansible.builtin.debug:
        var: mikrotik_export

    - name: Store export to local file
      ansible.builtin.copy:
        content: "{{ mikrotik_pass_export.stdout }}"
        dest: "{{ inventory_hostname }}.config"
        mode: '0755'
      delegate_to: localhost
      diff: true
      when: mikrotik_pass_export is defined
