---
all:
  children:
    mikrotik:
      hosts:
        vpn.qwaup.7357.ru:
        gw001-home.qwaup:
    servers:
      hosts:
        proxmox01.qwaup:
        dns01.qwaup:
        git01.qwaup:
        doc01.qwaup:
        run01.qwaup:
    smb:
      hosts:
        files.qwaup:
