---
all:
  children:
    mikrotik:
      hosts:
        chr001-ruvds:
          ansible_ssh_host: 45.8.228.114
        gw001-home-qwaup:
          ansible_ssh_host: 10.0.10.254
    servers:
      hosts:
        test-server:
          ansible_ssh_host: 10.0.10.235
