---

- name: Remove bad ppp
  community.routeros.command:
    commands: >-
      /ppp secret remove {{ item.name }}
  when: not item.account_enabled
  tags: configure_ppp_secrets

- name: Add ppp secret "{{ item.name }}"
  community.routeros.command:
    commands: >-
      /ppp secret add name={{ item.name }} password={{ item.password | default(default_user_password) }}
      profile=vpn-profile service=l2tp local-address={{ item.local_address }} remote-address={{ item.remote_address }}
      routes="{{ item.routes }}"
  when: item.account_enabled
  tags: configure_ppp_secrets
