---

- name: 0|add_pull
  ansible.builtin.include_tasks: 0.add_pull.yaml
  loop: "{{ chr_vpn_pools }}"
  tags: add_address_pool

- name: Set l2tp-server
  community.routeros.command:
    commands: >-
      /interface l2tp-server server set enabled=yes default-profile=vpn-profile
      use-ipsec=yes ipsec-secret="{{ default_user_password }}"

- name: Add vpn profile
  community.routeros.command:
    commands: >-
      /ppp profile add name=vpn-profile local-address={{ item.local_address }}
      remote-address={{ item.name }} use-encryption=yes only-one=yes dns-server=10.0.10.254
  loop: "{{ chr_vpn_pools }}"
  tags: add_profile

- name: 1|configure_ppp_secrets
  ansible.builtin.include_tasks: 1.configure_ppp_secrets.yaml
  loop: "{{ ppp_user_accounts }}"
  tags: configure_ppp_secrets
