---

- name: Add gpg key proxmox repository
  ansible.builtin.get_url:
    url: http://download.proxmox.com/debian/proxmox-release-bullseye.gpg
    dest: /etc/apt/trusted.gpg.d/proxmox-release-bullseye.gpg
    mode: '644'

- name: Add proxmox repository
  ansible.builtin.apt_repository:
    repo: deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription
    state: present
    filename: proxmox
