---
- name: 0|create_user
  ansible.builtin.include_tasks: 0.create_user.yaml
  loop: "{{ chr_user_accounts }}"
  tags: create_user

- name: 1|create_ssh_file
  ansible.builtin.include_tasks: 1.create_ssh_file.yaml
  loop: "{{ chr_user_accounts }}"
  tags: create_key

- name: Debug local_user
  ansible.builtin.debug:
    var: result_lookup.msg

- name: Get information about active users
  community.routeros.command:
    commands: >-
      user print detail where !disabled
  register: active_users

- name: Debug local_user
  ansible.builtin.debug:
    var: active_users

- name: 0|create_user
  ansible.builtin.include_tasks: 0.create_user.yaml

- name: Get information about active users 2
  community.routeros.command:
    commands: >-
      user print detail where !disabled
  register: active_users2

- name: Debug local_user
  ansible.builtin.debug:
    var: active_users2

# - name: Collect all facts from the device
#   community.routeros.facts:
#     gather_subset: all
#   register: facts
#
# - name: Debug local_user
#   ansible.builtin.debug:
#     var: facts
#
# - name: Information
#   community.routeros.command:
#     commands: >-
#       user print detail where !disabled
#   register: local_user
#
# - name: Debug local_user
#   ansible.builtin.debug:
#     var: local_user
