---

- name: Install sudo
  ansible.builtin.apt:
    name: sudo
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Add local users
  ansible.builtin.user:
    name: test
    password: "{{ item.password | default(default_user_password) | password_hash }}"
    groups: sudo, dip, plugdev, netdev
    shell: /bin/bash
  become: true
  vars:
    pwdhash: test
  loop: "{{ administrator_accounts }}"
