---

name: Deploy service powerdns
run-name: Deploy dns service
on:
  push:
    branches:
      - cd_dns
  paths:
    - 'roles/power-dns/**'

jobs:
  predeploy-dns:
    runs-on: self-hosted
    steps:
      - run: echo $SUPERSECRET > secret/key.yaml
        env:
          SUPERSECRET: ${{ secrets.SUPERSECRET }}
      - run: ansible-playbook playbook-power-dns.yaml --diff --check
      - run: rm -rfv secret/key.yaml
  deploy-dns:
    runs-on: self-hosted
    needs: [predeploy-dns]
    steps:
      - run: echo $SUPERSECRET > secret/key.yaml
        env:
          SUPERSECRET: ${{ secrets.SUPERSECRET }}
      - run: ansible-playbook playbook-power-dns.yaml --diff
      - run: rm -rfv secret/key.yaml
