name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  test-jobs:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: echo "test-jobs"
