---

name: Validation actions
run-name: Ansible and YAML checking
on: [push, pull_request]

jobs:
  syntax-check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: echo $SUPERSECRET > secret/pass.yaml
        env:
          SUPERSECRET: ${{ secrets.SUPERSECRET }}
      - run: ansible-playbook --syntax-check *.yaml
      - run: ansible-lint -v *.yaml
      - run: yamllint .
      - run: rm -rfv secret/*.yaml
